### ISSUE TITLE
No response to landmarks that aren't found

### ISSUE THREAD

**Issue by pangolingo** [ryanbateman/vision-bot#3]
The bot does not respond at all if you ask it for a landmark that it doesn't recognize. 
For instance: http://worldonline.media.clients.ellingtoncms.com/img/places/July_13_Number_2_030_r470x260_1_t670.jpg?b3f6a5d7692ccc373d56e40cf708e3fa67d9af9d

It does respond when it does recognize a landmark (Like the statue of Liberty).

**Comment by ryanbateman** [comment]
Yes, there's minimal error messaging at the moment (mostly because I don't know how best to refactor the messaging/error responses - the current 'pipeline' approach is pretty inelegant.)

**Comment by pangolingo** [comment]
This PR will add at least some error messaging. But I agree that it may be better to refactor all those if statements. #4
